In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

In [6]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

# Regression with ANN

In [7]:
from sklearn import datasets as skd

In [8]:
diabetes = skd.load_diabetes()

In [9]:
print(diabetes['DESCR'])

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, T-Cells (a type of white blood cells)
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, thyroid stimulating hormone
      - s5      ltg, lamotrigine
      - s6      glu, blood sugar level

Note: Each of these 10 feature va

In [10]:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [11]:
diabetes.get('feature_names')

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [12]:
diabetes.get('target')

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [13]:
from keras.datasets import boston_housing as bh

In [14]:
(xtrain,ytrain),(xtest,ytest)= bh.load_data()

In [15]:
xtrain[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [16]:
ytrain[0]

15.2

In [17]:
from keras.models import Sequential
from keras.layers import Dense

In [18]:
from keras.callbacks import EarlyStopping

In [19]:
es= EarlyStopping(patience=20)

In [20]:
model=Sequential()
model.add(Dense(activation='relu',input_shape=(13,),units=65))
model.add(Dense(activation='relu',units=65))
model.add(Dense(activation='relu',units=65))
model.add(Dense(activation='relu',units=65))
model.add(Dense(activation='relu',units=65))
model.add(Dense(activation='sigmoid',units = 1))
model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])

In [21]:
h=model.fit(xtrain,ytrain,epochs=1000,callbacks=[es])

Epoch 1/1000
13/13 [==============================] - 3s 13ms/step - loss: 569.0124 - mae: 22.0138
Epoch 2/1000
13/13 [==============================] - 0s 1ms/step - loss: 524.8560 - mae: 21.0496
Epoch 3/1000
13/13 [==============================] - 0s 1ms/step - loss: 547.8177 - mae: 21.3515
Epoch 4/1000
13/13 [==============================] - 0s 997us/step - loss: 546.2312 - mae: 21.3434
Epoch 5/1000
13/13 [==============================] - 0s 1ms/step - loss: 529.2705 - mae: 21.1488
Epoch 6/1000
13/13 [==============================] - 0s 1ms/step - loss: 548.7295 - mae: 21.4165
Epoch 7/1000
13/13 [==============================] - 0s 1ms/step - loss: 533.5062 - mae: 21.2776
Epoch 8/1000
13/13 [==============================] - 0s 1ms/step - loss: 567.6288 - mae: 21.8325
Epoch 9/1000
13/13 [==============================] - 0s 1ms/step - loss: 519.8477 - mae: 20.8704
Epoch 10/1000
13/13 [==============================] - 0s 1ms/step - loss: 510.4873 - mae: 20.7044
Epoch 11/1000
13

In [22]:
h.history

{'loss': [542.3704223632812,
  542.370361328125,
  542.3704223632812,
  542.370361328125,
  542.370361328125,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.370361328125,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704833984375,
  542.3704223632812,
  542.3704223632812,
  542.370361328125,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.370361328125,
  542.3704223632812,
  542.370361328125,
  542.370361328125,
  542.3704223632812,
  542.370361328125,
  542.3704223632812,
  542.3704223632812,
  542.3704223632812,
  542.370361328125,
  542.3704223632812,
  542.370361328125,
  542.3704223632812,
  542.3704833984375,
  542.3704223632812,
  542.3703002929688,
  542.370361328125,
  542.3704223632812,
  542.370361328125,
  542.370361328125

In [24]:
model.predict(xtest[0:2,:])

array([[1.],
       [1.]], dtype=float32)

In [25]:
model.save('bhmodel')

INFO:tensorflow:Assets written to: bhmodel\assets


In [26]:
import keras

In [27]:
m=keras.models.load_model('bhmodel')

In [28]:
m

# Recurrent Neural Network

In [29]:
stocks = pd.read_csv('stock_data.csv')

In [30]:
stocks.head()

Date     Open     High      Low    Close    Volume  OpenInt Stock
0  1984-09-07  0.42388  0.42902  0.41874  0.42388  23220030        0  AAPL
1  1984-09-10  0.42388  0.42516  0.41366  0.42134  18022532        0  AAPL
2  1984-09-11  0.42516  0.43668  0.42516  0.42902  42498199        0  AAPL
3  1984-09-12  0.42902  0.43157  0.41618  0.41618  37125801        0  AAPL
4  1984-09-13  0.43927  0.44052  0.43927  0.43927  57822062        0  AAPL

In [31]:
stocks['Stock'].value_counts()

AAPL    8364
MSFT    7983
TSLA    1858
FB      1381
Name: Stock, dtype: int64

In [32]:
msft = stocks[['Date','Open']][stocks['Stock']=='MSFT']

In [33]:
msft

Date      Open
10222  1986-03-13   0.06720
10223  1986-03-14   0.07533
10224  1986-03-17   0.07533
10225  1986-03-18   0.07533
10226  1986-03-19   0.07533
...           ...       ...
18200  2017-11-06  84.20000
18201  2017-11-07  84.77000
18202  2017-11-08  84.14000
18203  2017-11-09  84.11000
18204  2017-11-10  83.79000

[7983 rows x 2 columns]

In [34]:
7983/50

159.66

In [35]:
x=[]
y=[]
for i in range(100,len(msft)):
    x.append(msft['Open'].values[i-100:i])
    y.append(msft['Open'].values[i])
x=np.array(x)
y=np.array(y)

In [36]:
len(x)

7883

In [37]:
len(y)

7883

In [38]:
x = np.reshape(x,(x.shape[0],x.shape[1],1))


In [39]:
x.shape


(7883, 100, 1)

In [40]:
from keras.layers import LSTM

In [41]:
model = Sequential()
model.add(LSTM(units=200, return_sequences=True, input_shape=(100,1)))
model.add(LSTM(units=200, return_sequences=True))
model.add(LSTM(units=200, return_sequences=True))
model.add(LSTM(units=200, return_sequences=True))
model.add(LSTM(units=200, return_sequences=True))
model.add(LSTM(units=200))
model.add(Dense(units=1))
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae','accuracy'])

In [ ]:
model.fit(x,y, epochs=10, batch_size=50)


Epoch 1/10
158/158 [==============================] - 235s 1s/step - loss: 198.5341 - mae: 8.4659 - accuracy: 0.0000e+00
Epoch 2/10
106/158 [===================>..........] - ETA: 1:21 - loss: 108.1202 - mae: 6.2301 - accuracy: 0.0000e+00