### Numpy and pandas

In [3]:
import numpy as np
import pandas as pd

In [9]:
#Creating numpy array
a= np.array([1,4,6,7,8,3])
print(a)

[1 4 6 7 8 3]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
#accessing element
a[0]

1

In [9]:
a=np.array([[4,8,3,11],[2,9,6,12],[1,2,7,13]])
a

array([[ 4,  8,  3, 11],
       [ 2,  9,  6, 12],
       [ 1,  2,  7, 13]])

In [11]:
a.shape

(3, 4)

In [14]:
a.sum()

78

In [15]:
a.mean()

6.5

In [16]:
a.max()

13

In [17]:
a.min()

1

In [12]:
a.sum(axis=1)

array([26, 29, 23])

In [15]:
a[1,1:3]

array([9, 6])

In [16]:
a[:2,3]

array([11, 12])

In [4]:
#3D matrix
b = np.array([[[4,41],[8,81],[3,31],[11,111]],[[2,21],[9,91],[6,61],[12,121]],[[1,11],[2,21],[7,71],[13,131]]])
print(b)

[[[  4  41]
  [  8  81]
  [  3  31]
  [ 11 111]]

 [[  2  21]
  [  9  91]
  [  6  61]
  [ 12 121]]

 [[  1  11]
  [  2  21]
  [  7  71]
  [ 13 131]]]


In [5]:
b.shape

(3, 4, 2)

In [7]:
b.sum()

870

In [8]:
b.sum(axis=0)

array([[  7,  73],
       [ 19, 193],
       [ 16, 163],
       [ 36, 363]])

In [13]:
b.sum(axis=1)

array([[ 26, 264],
       [ 29, 294],
       [ 23, 234]])

In [21]:
b[0,0]=34

In [23]:
b.sum()

870

In [24]:
b.sum(axis=0)

array([[  7,  73],
       [ 19, 193],
       [ 16, 163],
       [ 36, 363]])

In [25]:
#functions to create array

In [26]:
a1= np.linspace(1,100,5) #no. of values i.e 5

In [27]:
a1

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [28]:
a2=np.arange(1,100,5) # gap of 5 
a2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [30]:
np.ones(4)

array([1., 1., 1., 1.])

In [31]:
np.zeros(4)

array([0., 0., 0., 0.])

In [32]:
np.random.rand(1)

array([0.28347406])

In [33]:
np.random.randint(1,100,3)

array([30, 54, 20])

In [34]:
a

array([[34,  8,  3, 11],
       [ 2,  9,  6, 12],
       [ 1,  2,  7, 13]])

In [35]:
a.reshape(6,2)

array([[34,  8],
       [ 3, 11],
       [ 2,  9],
       [ 6, 12],
       [ 1,  2],
       [ 7, 13]])

In [36]:
np.hsplit(a,2) #2 is no of parts here

[array([[34,  8],
        [ 2,  9],
        [ 1,  2]]),
 array([[ 3, 11],
        [ 6, 12],
        [ 7, 13]])]

### Pandas

In [19]:
s1=pd.Series([4,6,8,3,2,9])
s1

0    4
1    6
2    8
3    3
4    2
5    9
dtype: int64

In [20]:
s2=pd.Series({'a':3,'b':[4,5,6],'c':30})
s2

a            3
b    [4, 5, 6]
c           30
dtype: object

In [21]:
s2['a']    #using  keys

3

In [22]:
s2[0] #using index numbers

3

In [23]:
s1.dtype

dtype('int64')

In [24]:
s1.size

6

In [25]:
s1.head()

0    4
1    6
2    8
3    3
4    2
dtype: int64

In [44]:
s1.tail()

1    6
2    8
3    3
4    2
5    9
dtype: int64

In [45]:
s1.sample(3)

3    3
2    8
4    2
dtype: int64

In [46]:
#Accessing series s[0]
#inserting   s1[9]=20
#assignment   s1[0] =2
#deletion    del s1[3]

In [48]:
df=pd.DataFrame([4,5,6,8,3,2,9,5])
df

0
0  4
1  5
2  6
3  8
4  3
5  2
6  9
7  5

In [50]:
pd.DataFrame([4,5,6],index=['a','b','c'],columns=['Data'])

Data
a     4
b     5
c     6

In [27]:
pd.Series([1,2,3,4],index=['a','b','c','d'],name="Data")

a    1
b    2
c    3
d    4
Name: Data, dtype: int64

In [30]:
df1=pd.DataFrame([[4,'went',6],[56,'go',30],[20,'wow',34]],columns=['Data','Count','Val'])
df1

Data Count  Val
0     4  went    6
1    56    go   30
2    20   wow   34

In [28]:
pd.Series([[4,'went',6],[56,'go',30],[20,'wow',34]])

0     [4, went, 6]
1     [56, go, 30]
2    [20, wow, 34]
dtype: object

In [56]:
#Acessing column data
df1['Count']

0    went
1      go
2     wow
Name: Count, dtype: object

In [32]:
#ACCESSING MULTI-COLUMNS
df1[['Count','Data']]

Count  Data
0  went     4
1    go    56
2   wow    20

In [33]:
df1[['Count']]         #it gives view of dataframe

Count
0  went
1    go
2   wow

In [40]:
del df1['Data']

In [41]:
df1

Count
0  went
1    go
2   wow

In [43]:
#Accessing row data in Df
df1.loc[1]

Count    go
Name: 1, dtype: object

In [60]:
df1.head(2)

Data Count  Val
0     4  went    6
1    56    go   30

In [64]:
#conversion to array
df1.values   #DataFrame
s1.values   #series

array([4, 6, 8, 3, 2, 9], dtype=int64)

In [44]:
pd.read_json('sample2.json')

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.